config/routes.rb
Rails.application.routes.draw do
  get '/admin' => redirect("/users/sign_in")
  devise_for :users, controllers: { sessions: 'admin/sessions' }

  namespace :api do
    get '/posts/published', to: 'posts#published'
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :archive, on: :member
    end

    resources :contractors do
      resources :contacts
    end
    get 'contacts/:contractor_name', to: 'contacts#show'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index, :show, :new, :create] do
    collection do
      get  :feeds, defaults: { format: 'rss' }
      post :tweet
      get :home
    end
  end
  get 'posts/tags/:tag', to: 'posts#tags', as: 'posts_tag_filter'

  get '/obrigado-anuncio-enviado-com-sucesso' => 'posts#success', as: :post_success

  get '/feedback', to: 'home#feedback', as: :feedback
end

app/views/shared/404.html.erb
<% title('Página não encontrada') %>
<% content_for :meta do %>
<meta name="robots" content="noindex">
<% end %>

<div class="page_not_found">
  <h1>Página não encontrada :(</h1>
  <p>A página solicitada não existe.</p>
  <%= link_to 'Retornar para a página de anúncios', root_path %>
</div>

app/views/shared/_default_right_sidebar.html.erb
<script type="text/javascript"><!--
  google_ad_client = "ca-pub-1679261120441100";
  /* 300x250 main jobs, right sidebar */
  google_ad_slot = "7216256845";
  google_ad_width = 300;
  google_ad_height = 250;
  //-->
</script>

<script type="text/javascript"
  src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>

<br><br>

<div class='panel'>
  <h5>Redes Sociais</h5>
  <p>
    <iframe src="//www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fshigotodoko&amp;width=292&amp;height=240&amp;show_faces=true&amp;colorscheme=light&amp;stream=false&amp;show_border=true&amp;header=true&amp;appId=143661522361941" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:292px; height:190px; background-color: #EEE;" allowTransparency="false"></iframe>

    <a href="http://twitter.com/shigotodoko" class="twitter-follow-button" data-show-count="true" data-lang="pt-BR" data-size="large">Seguir @shigotodoko</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </p>
</div>

<div class='panel'>
  <h5>Feeds</h5>
  <form action="http://feedburner.google.com/fb/a/mailverify" method="post" target="popupwindow" onsubmit="window.open('http://feedburner.google.com/fb/a/mailverify?uri=Shigotodoko', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true">
    <p>Receba novos anúncios por e-mail</p>
    <p><input type="text" name="email" placeholder='Digite seu e-mai..'></p>
    <input type="hidden" value="Shigotodoko" name="uri"/>
    <input type="hidden" name="loc" value="pt_BR">
    <input type="submit" value="Assinar" class="success small button">
  </form>
</div>

<% if signed_in? && current_user.admin? %>
  <p><%= link_to 'Sair', destroy_user_session_path, method: :delete %></p>
  <p><%= link_to 'Novo anúncio', new_post_path, class: 'tiny success button' %></p>
  <p><%= link_to 'Nova empreiteira', new_contractor_path, class: 'small success button' %></p>
<% end %>

<div class='provinces-list'>
  <h5 data-tooltip class='top-bottom has-tip' title='Filtre anúncios por uma região específica através das tags :)'>Tags</h5>
  <ul class='square side-nav'>
    <% @tags.each do |tag| %>
      <li><%= link_to tag.name, posts_tag_filter_path(tag.name) %></li>
    <% end %>
  </ul>
</div>

<div class='links'>
  <ul>
    <li>© 2013 Shigotodoko</li>
    <li><a href='/sobre'>Sobre o site</a></li>
    <li><a href='https://docs.google.com/forms/d/1OVE-B8-VQjrK6VtmCOK39zdmbTYoCfjtvQdiMALaAKg/viewform'>Feedback</a></li>
  </ul>
</div>

<%= link_to 'Enviar anúncio grátis', new_post_from_web_path, class: 'tiny success button has-tip top-bottom', title: 'Seu anúncio é grátis por 30 dias!' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.present? %>
  <ul class='error_messages_list'>
  <% object.errors.full_messages.each do |error_message| %>
    <li><%= error_message %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_facebook_sdk.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.async = true;
js.src = "//connect.facebook.net/pt_BR/all.js#xfbml=1&appId=143661522361941";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_top_banner.html.erb
<div class='ad-320-568 header align-mobile-ad'>
  <!-- 320x50 mobile-top -->
  <ins class="adsbygoogle"
    style="display:inline-block;width:320px;height:50px"
    data-ad-client="ca-pub-1679261120441100"
    data-ad-slot="9229091613"></ins>
  <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div>

<div class='ad-from-768 header align-mobile-ad'>
  <!-- (new) 728x90 main jobs - header -->
  <ins class="adsbygoogle"
    style="display:inline-block;width:728px;height:90px"
    data-ad-client="ca-pub-1679261120441100"
    data-ad-slot="4600877081"></ins>
  <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
</div>