config/routes.rb
Rails.application.routes.draw do
  get '/admin' => redirect("/users/sign_in")
  devise_for :users, controllers: { sessions: 'admin/sessions' }

  namespace :api do
    get '/posts/published', to: 'posts#published'
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :archive, on: :member
    end

    resources :contractors do
      resources :contacts
    end
    get 'contacts/:contractor_name', to: 'contacts#show'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index, :show, :new, :create] do
    collection do
      get  :feeds, defaults: { format: 'rss' }
      post :tweet
      get :home
    end
  end
  get 'posts/tags/:tag', to: 'posts#tags', as: 'posts_tag_filter'

  get '/obrigado-anuncio-enviado-com-sucesso' => 'posts#success', as: :post_success

  get '/feedback', to: 'home#feedback', as: :feedback
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contractor
  has_one :contactable
  has_one :contact, through: :contactable

  scope :all_for_api, -> {
    select(:id,
           :title,
           :location,
           'SUBSTR(description, 1,150) as description',
           :published_at,
           :created_at,
           :expired_at,
           :status)
    .order('id DESC')
  }

  scope :for_listing, -> { where("published_at IS NOT NULL").order("id DESC") }
  scope :published,   -> { where(status: 'published') }
  scope :expired,     -> { where(status: 'expired') }

  attr_accessor :contractor_company_name, :contractor_person_name, :contractor_phone_number, :contractor_mail_address, :contractor_address

  validates :title, :location, :description, :salary, :shift, :day_off, :work_load, presence: true

  validates :contractor, presence: true, on: :admin

  with_options({on: :web}) do |for_user|
    for_user.validates :contractor_person_name, :contractor_company_name, :contractor_address, :contractor_phone_number, presence: true

    for_user.validates :contractor_mail_address, presence: true, format: { with:  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  end

  enum status: [:pending, :published, :expired, :cancelled, :archived]

  acts_as_taggable

  def publish
    self.active = true
    self.published_at = Time.now
    self.published!
    self.save!(context: :admin)
  end

  def expire
    self.active = false
    self.expired_at = Time.now
    self.expired!
    self.save!(validate: false)
  end

  def archive
    self.archived!
    self.save!(context: :admin)
  end

  def relateds
    Posts::RelatedPosts.find(self)
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < AdminController
    def index
      @posts = Post.all.includes(:contractor).order(id: 'desc').paginate(page: params[:page], per_page: results_per_page)
    end

    def show
      @post = Post.includes(:contractor).where(id: params[:id]).first!
    end

    def edit
      @post = Post.includes(:contractor).where(id: params[:id]).first
      @contractors = Contractor.all
    end

    def update
      @post = Post.where(id: params[:id]).first

      set_tag_list_to_post_params(@post)

      if @post.update_attributes(post_params)
        redirect_to(admin_post_url(@post), notice: "Anúncio salvo com sucesso!")
      else
        flash[:error] = "Não foi possível salvar o anúncio"
        render :edit
      end
    end

    def publish
      @post = Post.find(params[:id])
      @post.publish

      redirect_to(admin_post_url(@post), notice: "Anúncio publicado com sucesso!")
    end

    def archive
      @post = Post.find(params[:id])
      @post.archive

      redirect_to(admin_post_url(@post), notice: "Anúncio arquivado com sucesso!")
    end

    protected

    def results_per_page
      WillPaginate.per_page = 100
    end

    def post_params
      params.require(:post).permit(
        :title, :location, :description, :requirements, :benefits,
        :salary, :shift, :day_off, :notes, :contractor_id, :contact_id, :tag_list
      )
    end

    def set_tag_list_to_post_params(post)
      provinces = tag_service(post_params["location"]).call
      @post.tag_list.add(provinces)
    end

    def tag_service(location)
      TagService.new(location)
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    def published
      posts = Post.published
      render json: posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  respond_to :html

  def home
  end

  def feeds
    @posts = Post.published

    respond_to do |format|
      format.html
      format.rss  { render layout: false }
      format.atom { redirect_to feeds_posts_path(format: :rss), status: :moved_permanently }
    end
  end

  def index
    @posts = Post.for_listing.
      paginate(page: params[:page], per_page: 10).decorate

    if stale?(@posts)
      respond_with(@posts)
    end
  end

  def tags
    @posts = Post.for_listing
      .tagged_with(params[:tag])
      .paginate(page: params[:page], per_page: 10)
      .includes([:contractor, :tags]).decorate

      render action: :index
  end

  def show
    post = Post.where(id: params[:id]).includes(:contractor).first!

    @post = PostDecorator.decorate(post)

    respond_with(@post)
  end

  def new
    @post = Post.new(active: false)

    respond_with(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.notes = ContractorParser.call(post_params)

    if @post.save(context: :web)
      Mailer.notify(params[:post]).deliver_now
      render :success
    else
      render :new
    end
  end

  def success; end

  private

  def record_not_found
    respond_to do |format|
      format.html { render layout: 'application',
                    template: 'shared/404',
                    status: 404 }
      format.all { render nothing: true, status: 404 }
    end
  end

  def post_params
    params.require(:post).permit(:title, :location, :salary, :shift, :day_off,
                                :description, :requirements, :benefits, :work_load,
                                :contractor_person_name,
                                :contractor_company_name,
                                :contractor_address,
                                :contractor_mail_address,
                                :contractor_phone_number)
  end
end

app/helpers/admin/posts_helper.rb
module Admin
  module PostsHelper
    def will_paginate(collection_or_options = nil, options = {})
      if collection_or_options.is_a? Hash
	options, collection_or_options = collection_or_options, nil
      end
      unless options[:renderer]
	options = options.merge :renderer => MyCustomLinkRenderer if options[:admin]
      end
      super *[collection_or_options, options].compact
    end

    def title(title)
      title.truncate(50)
    end

    def location(location)
      location.truncate(30)
    end

    def status(post)
      return content_tag(:span, post.status, class: "new badge blue", :"data-badge-caption"=> "") if post.pending?
      return content_tag(:span, post.status, class: "new badge green", :"data-badge-caption"=> "") if post.published?
      return content_tag(:span, post.status, class: "new badge red", :"data-badge-caption"=> "") if post.expired?
      return content_tag(:span, post.status, class: "new badge orange", :"data-badge-caption"=> "") if post.archived?
    end

    def contractor_name(post)
      no_contractor_message = "Anúncio sem empresa anunciante"

      return no_contractor_message if post.pending?

      if post.contractor
        link_to(post.contractor.name, admin_contractor_path(post.contractor))
      else
        no_contractor_message
      end
    end

    def contractor_list
      Contractor.all.collect { |contractor| [contractor.name, contractor.id] }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper

  def ribbon(post)
    if post.expired?
      content_tag(:div, nil, class: "ribbon") do
        content_tag(:span, "Expirado", class: "expired")
      end
    elsif post.recent_published?
      content_tag(:div, nil, class: "ribbon") do
        content_tag(:span, "Novo!", class: "new")
      end
    end
  end

  def resume(description = post.description)
    description.truncate(150)
  end

  def visit(post)
    link_to(content_tag(:label, "ver anúncio"), post_path(post), class: "view")
  end
end

app/views/admin/posts/_posts_table.html.erb
<div class="card-panel hoverable">
  <div class="card-content">
    <h4>Anúncios</h4>
    <%= will_paginate(posts, admin: true) %>

    <table>
      <thead>
        <tr>
          <th data-field="title">Título</th>
          <th data-field="region">Região</th>
          <th data-field="company_name">Anunciante</th>
          <th data-field="created_at">Criado em</th>
          <th data-field="status"></th>
        </tr>
      </thead>

      <tbody>
        <% posts.each do |post| %>
          <tr>
            <td><%= link_to title(post.title), admin_post_path(post) %></td>
            <td><%= location(post.location) %></td>
            <td><%= contractor_name(post) %></td>
            <td><%= I18n.l(post.created_at, format: "%d/%m/%Y") %></td>
            <td><%= status(post) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate(posts, admin: true) %>

  </div>
</div>

app/views/admin/posts/edit.html.erb
<div class="row">
  <h3><%= status(@post) %></h3>
  <%= form_for([:admin, @post], class: "col s12") do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :title, class: "validate" %>
        <%= f.text_field :title, value: @post.title, required: true %>
      </div>
      <div class="input-field col s6">
        <%= f.label :location, class: "validate" %>
        <%= f.text_field :location, value: @post.location, required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.label :description, class: "validate" %>
        <%= f.text_area :description, value: @post.description, class: "materialize-textarea", required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.label :requirements, class: "validate" %>
        <%= f.text_area :requirements, value: @post.requirements, class: "materialize-textarea" %>
      </div>
      <div class="input-field col s12">
        <%= f.label :benefits, class: "validate" %>
        <%= f.text_area :benefits, value: @post.benefits, class: "materialize-textarea" %>
      </div>
      <div class="input-field col s12">
        <%= f.label :salary, class: "validate" %>
        <%= f.text_field :salary, value: @post.salary, required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.label :shift, class: "validate" %>
        <%= f.text_field :shift, value: @post.shift, required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.label :day_off, class: "validate" %>
        <%= f.text_field :day_off, value: @post.day_off, required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.label :work_load, class: "validate" %>
        <%= f.text_field :work_load, value: @post.work_load, required: true %>
      </div>
      <div class="input-field col s12">
        <%= f.label :notes, class: "validate" %>
        <%= f.text_area :notes, value: @post.notes, class: "materialize-textarea" %>
      </div>
      <div class="input-field col s12">
        <%= f.select :contractor_id, contractor_list %>
        <%= f.label :contractor_id, class: "validate" %>
      </div>
    </div>
    <div class="card-action">
      <button class="btn waves-effect waves-light" type="submit" name="action">Salvar
        <i class="material-icons right">send</i>
      </button>
    </div>
  <% end %>
</div>

app/views/admin/posts/index.html.erb
<%= render 'posts_table', posts: @posts %>

app/views/admin/posts/show.html.erb
<% flash.each do |name, msg| %>
  <div id="card-alert" class="card green">
    <div class="card-content white-text">
      <p><i class="mdi-navigation-check"></i><%= msg %></p>
    </div>
  </div>
<% end %>

<div class="card-panel hoverable">
  <div class="card-content">
    <h3><%= status(@post) %></h3>
    <h2><%= @post.title %></h2>
    <p><%= @post.location %></p>
    <h5>Descrição</h5>
    <p><%= simple_format(@post.description) %></p>
    <h5>Requisitos</h5>
    <p><%= simple_format(@post.requirements) %></p>
    <h5>Benefícios</h5>
    <p><%= simple_format(@post.benefits) %></p>
    <h5>Salário</h5>
    <p><%= @post.salary %></p>
    <h5>Turno</h5>
    <p><%= @post.shift %></p>
    <h5>Folga</h5>
    <p><%= @post.day_off %></p>
    <h5>Horário de trabalho</h5>
    <p><%= @post.work_load %></p>
    <h5>Notas adicionais</h5>
    <p><%= simple_format(@post.notes) %></p>
    <h5><%= contractor_name(@post) %></h5>
  </div>
  <div class="card-action">
    <%= link_to "Editar", edit_admin_post_url(@post), class: "waves-effect waves-light btn" %>
    <%= link_to "Publicar", publish_admin_post_url(@post), method: "put", class: "waves-effect waves-light btn" %>
    <%= link_to "Arquivar", archive_admin_post_url(@post), method: "put", class: "waves-effect waves-light btn" %>
  </div>
</div>