config/routes.rb
Rails.application.routes.draw do
  get '/admin' => redirect("/users/sign_in")
  devise_for :users, controllers: { sessions: 'admin/sessions' }

  namespace :api do
    get '/posts/published', to: 'posts#published'
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :archive, on: :member
    end

    resources :contractors do
      resources :contacts
    end
    get 'contacts/:contractor_name', to: 'contacts#show'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index, :show, :new, :create] do
    collection do
      get  :feeds, defaults: { format: 'rss' }
      post :tweet
      get :home
    end
  end
  get 'posts/tags/:tag', to: 'posts#tags', as: 'posts_tag_filter'

  get '/obrigado-anuncio-enviado-com-sucesso' => 'posts#success', as: :post_success

  get '/feedback', to: 'home#feedback', as: :feedback
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :contractor
  has_one :contactable
  has_one :contact, through: :contactable

  scope :all_for_api, -> {
    select(:id,
           :title,
           :location,
           'SUBSTR(description, 1,150) as description',
           :published_at,
           :created_at,
           :expired_at,
           :status)
    .order('id DESC')
  }

  scope :for_listing, -> { where("published_at IS NOT NULL").order("id DESC") }
  scope :published,   -> { where(status: 'published') }
  scope :expired,     -> { where(status: 'expired') }

  attr_accessor :contractor_company_name, :contractor_person_name, :contractor_phone_number, :contractor_mail_address, :contractor_address

  validates :title, :location, :description, :salary, :shift, :day_off, :work_load, presence: true

  validates :contractor, presence: true, on: :admin

  with_options({on: :web}) do |for_user|
    for_user.validates :contractor_person_name, :contractor_company_name, :contractor_address, :contractor_phone_number, presence: true

    for_user.validates :contractor_mail_address, presence: true, format: { with:  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
  end

  enum status: [:pending, :published, :expired, :cancelled, :archived]

  acts_as_taggable

  def publish
    self.active = true
    self.published_at = Time.now
    self.published!
    self.save!(context: :admin)
  end

  def expire
    self.active = false
    self.expired_at = Time.now
    self.expired!
    self.save!(validate: false)
  end

  def archive
    self.archived!
    self.save!(context: :admin)
  end

  def relateds
    Posts::RelatedPosts.find(self)
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < AdminController
    def index
      @posts = Post.all.includes(:contractor).order(id: 'desc').paginate(page: params[:page], per_page: results_per_page)
    end

    def show
      @post = Post.includes(:contractor).where(id: params[:id]).first!
    end

    def edit
      @post = Post.includes(:contractor).where(id: params[:id]).first
      @contractors = Contractor.all
    end

    def update
      @post = Post.where(id: params[:id]).first

      set_tag_list_to_post_params(@post)

      if @post.update_attributes(post_params)
        redirect_to(admin_post_url(@post), notice: "Anúncio salvo com sucesso!")
      else
        flash[:error] = "Não foi possível salvar o anúncio"
        render :edit
      end
    end

    def publish
      @post = Post.find(params[:id])
      @post.publish

      redirect_to(admin_post_url(@post), notice: "Anúncio publicado com sucesso!")
    end

    def archive
      @post = Post.find(params[:id])
      @post.archive

      redirect_to(admin_post_url(@post), notice: "Anúncio arquivado com sucesso!")
    end

    protected

    def results_per_page
      WillPaginate.per_page = 100
    end

    def post_params
      params.require(:post).permit(
        :title, :location, :description, :requirements, :benefits,
        :salary, :shift, :day_off, :notes, :contractor_id, :contact_id, :tag_list
      )
    end

    def set_tag_list_to_post_params(post)
      provinces = tag_service(post_params["location"]).call
      @post.tag_list.add(provinces)
    end

    def tag_service(location)
      TagService.new(location)
    end
  end
end

app/controllers/api/posts_controller.rb
module Api
  class PostsController < ApplicationController
    def published
      posts = Post.published
      render json: posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  respond_to :html

  def home
  end

  def feeds
    @posts = Post.published

    respond_to do |format|
      format.html
      format.rss  { render layout: false }
      format.atom { redirect_to feeds_posts_path(format: :rss), status: :moved_permanently }
    end
  end

  def index
    @posts = Post.for_listing.
      paginate(page: params[:page], per_page: 10).decorate

    if stale?(@posts)
      respond_with(@posts)
    end
  end

  def tags
    @posts = Post.for_listing
      .tagged_with(params[:tag])
      .paginate(page: params[:page], per_page: 10)
      .includes([:contractor, :tags]).decorate

      render action: :index
  end

  def show
    post = Post.where(id: params[:id]).includes(:contractor).first!

    @post = PostDecorator.decorate(post)

    respond_with(@post)
  end

  def new
    @post = Post.new(active: false)

    respond_with(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.notes = ContractorParser.call(post_params)

    if @post.save(context: :web)
      Mailer.notify(params[:post]).deliver_now
      render :success
    else
      render :new
    end
  end

  def success; end

  private

  def record_not_found
    respond_to do |format|
      format.html { render layout: 'application',
                    template: 'shared/404',
                    status: 404 }
      format.all { render nothing: true, status: 404 }
    end
  end

  def post_params
    params.require(:post).permit(:title, :location, :salary, :shift, :day_off,
                                :description, :requirements, :benefits, :work_load,
                                :contractor_person_name,
                                :contractor_company_name,
                                :contractor_address,
                                :contractor_mail_address,
                                :contractor_phone_number)
  end
end

app/helpers/admin/posts_helper.rb
module Admin
  module PostsHelper
    def will_paginate(collection_or_options = nil, options = {})
      if collection_or_options.is_a? Hash
	options, collection_or_options = collection_or_options, nil
      end
      unless options[:renderer]
	options = options.merge :renderer => MyCustomLinkRenderer if options[:admin]
      end
      super *[collection_or_options, options].compact
    end

    def title(title)
      title.truncate(50)
    end

    def location(location)
      location.truncate(30)
    end

    def status(post)
      return content_tag(:span, post.status, class: "new badge blue", :"data-badge-caption"=> "") if post.pending?
      return content_tag(:span, post.status, class: "new badge green", :"data-badge-caption"=> "") if post.published?
      return content_tag(:span, post.status, class: "new badge red", :"data-badge-caption"=> "") if post.expired?
      return content_tag(:span, post.status, class: "new badge orange", :"data-badge-caption"=> "") if post.archived?
    end

    def contractor_name(post)
      no_contractor_message = "Anúncio sem empresa anunciante"

      return no_contractor_message if post.pending?

      if post.contractor
        link_to(post.contractor.name, admin_contractor_path(post.contractor))
      else
        no_contractor_message
      end
    end

    def contractor_list
      Contractor.all.collect { |contractor| [contractor.name, contractor.id] }
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper

  def ribbon(post)
    if post.expired?
      content_tag(:div, nil, class: "ribbon") do
        content_tag(:span, "Expirado", class: "expired")
      end
    elsif post.recent_published?
      content_tag(:div, nil, class: "ribbon") do
        content_tag(:span, "Novo!", class: "new")
      end
    end
  end

  def resume(description = post.description)
    description.truncate(150)
  end

  def visit(post)
    link_to(content_tag(:label, "ver anúncio"), post_path(post), class: "view")
  end
end

app/views/posts/_adsense_right.html.erb
<div class="adsense">
  <h1>Publicidade</h1>
  <div class="adsense_main_jobs_sidebar">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- (new) 336x280 main jobs - sidebar -->
    <ins class="adsbygoogle"
      style="display:inline-block;width:336px;height:280px"
      data-ad-client="ca-pub-1679261120441100"
      data-ad-slot="8362671732"></ins>
    <script>
(adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
</div><!-- /adsense -->

app/views/posts/_fb_likebox.html.erb
<div class="social_fb_likebox">
  <div class="fb-like-box" data-href="https://www.facebook.com/shigotodoko" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
</div>

app/views/posts/_google_plus.html.erb
<!-- Place this tag in your head or just before your close body tag. -->
<script src="https://apis.google.com/js/platform.js" async defer>
  {lang: 'pt-BR'}
</script>

<!-- Place this tag where you want the widget to render. -->
<div class='social_g-page'>
  <div class="g-page" data-href="//plus.google.com/u/0/111043374287269601303" data-layout="landscape" data-rel="publisher"></div>
</div>

app/views/posts/_list_map.html.erb
<!-- header adsense -->
<div class="adsense_main_jobs_header">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- (new) 728x90 main jobs - header -->
  <ins class="adsbygoogle"
    style="display:inline-block;width:728px;height:90px"
    data-ad-client="ca-pub-1679261120441100"
    data-ad-slot="4600877081"></ins>
  <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>
<!-- /header adsense -->

<div class="ct_left">
  <%= render 'posts' %>
</div><!-- /ct_left -->

<div class="ct_right">
  <%= render partial: 'layouts/ct_right' %>

  <div class="adsense_main_jobs_sidebar">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- (new) 336x280 main jobs - sidebar -->
    <ins class="adsbygoogle"
      style="display:inline-block;width:336px;height:280px"
      data-ad-client="ca-pub-1679261120441100"
      data-ad-slot="8362671732"></ins>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div><!-- /adsense -->

  <div class="social_twitter_follow">
    <a href="https://twitter.com/shigotodoko" class="twitter-follow-button" data-show-count="true" data-show-screen-name="true" data-lang="pt" data-size="large">Seguir @Shigotodoko</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>

  <div class="social_fb_likebox">
    <div class="fb-like-box" data-href="https://www.facebook.com/shigotodoko" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
  </div>

</div><!-- /ct_right -->

app/views/posts/_partners.html.erb
<section class="partners">
  <h2><a href='http://www.japaoemfoco.com/como-receber-o-reembolso-da-aposentadoria-no-brasil/' title='Saiba como receber o reembolso da aposentadoria no Brasil' target='_blank'>Saiba como receber o reembolso da aposentadoria no Brasil</a></h2>
  <p>parceiro:<a href='http://japaoemfoco.com' title='parceiro: japaoemfoco.com' target='_blank'> japaoemfoco.com</a></p>
</section>

<section class='announcements'>
  <p>Você tem um site ou um blog e gostaria de ser nosso parceiro de conteúdo?</p>
  <p>Entre em contato conosco: <%=mail_to('shigotodoko@gmail.com')%></p>
</section>

app/views/posts/_post.html.erb
<div class="item">
  <h1><%= link_to(post.title, post_path(post)) %></h1>

  <div class="int">
    <span><strong><%= post.contractor.name %></strong> - <%= post.location %></span>
    <p><%= resume(post.description) %></p>
    <p class='published_date'>Publicado há <%= time_ago_in_words(post.published_at) %> atrás</p>
    <div class="social_tags">
      <div class="fb">
        <iframe src="//www.facebook.com/plugins/like.php?href=http://www.shigotodoko.com/posts/<%= post.id %>&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=80&amp;appId=451607958239374" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:80px;" allowTransparency="true"></iframe>
      </div>

      <div class="tt">
        <a href="https://twitter.com/share"
          class="twitter-share-button"
          data-related="klebershimabuku"
          data-via="shigotodoko"
          data-lang="pt_BR"
          data-count="horizontal"
          data-text="<%= post.title %>"
          data-url="http://www.shigotodoko.com<%= url_for(post) %>">
          Tweet
        </a>
      </div>

      <%= visit(post) %>
      <% post.tags.each do |tag| %>
        <%= link_to tag, posts_tag_filter_path(tag.name), class: 'tag' %>
    <% end %>
    </div>
  </div>
</div>

app/views/posts/_twitter_follow.html.erb
<div class="social_twitter_follow">
  <a href="https://twitter.com/shigotodoko" class="twitter-follow-button" data-show-count="true" data-show-screen-name="true" data-lang="pt" data-size="large">Seguir @Shigotodoko</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
</div>

app/views/posts/home.html.erb
<div class="section1">
    <div class="ct">
        <div class="base">
            <div id="parallax">
                <span class="logo"></span>
                <div class="container">
                    <div class="ct_left">
                        <div id="scroller">
                        <div class="item">
                            <h1>Atendente de loja<span><strong>2 min</strong> atrás</span></h1>
                            <div class="int">
                                <span><strong>Ginza Mitsukoshi</strong> - Shizuoka</span>
                                <p>Atiam facilisis eleifend quam in molestie. Curabitur feugiat non risus vitae dapibus. Suspendisse nisi augue, consequat quis tortor ac, condimentum aliquam nunc.</p>
                                <div class="social_tags">
                                    <a class="fb"></a>
                                    <a class="gp"></a>
                                    <a class="tt"></a>
                                    <a class="view"><label>ver anuncio</label></a>
                                    <label>moda</label>
                                    <label>shizuoka</label>
                                </div>
                            </div>
                        </div>
                        <div class="item">
                            <h1>Atendente de loja<span><strong>2 min</strong> atrás</span></h1>
                            <div class="int">
                                <span><strong>Versace</strong> - Shizuoka</span>
                                <p>Atiam facilisis eleifend quam in molestie. Curabitur feugiat non risus vitae dapibus. Suspendisse nisi augue, consequat quis tortor ac, condimentum aliquam nunc.</p>
                                <div class="social_tags">
                                    <a class="fb"></a>
                                    <a class="gp"></a>
                                    <a class="tt"></a>
                                    <a class="view"><label>ver anuncio</label></a>
                                    <label>moda</label>
                                    <label>shizuoka</label>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                </div>
                </div>
                
            </div>
        </div>
    </div>
</div>

<div class="section2">
    <div class="ct">
        <div class="text">
            <h1>Sobre</h1>
            <p>
                Qui an minim iudicem, ab fore ea dolore, se mandaremus voluptatibus iis vidisse 
                imitarentur ne laborum. Singulis nisi varias probant fore, ita noster 
                cohaerescant. Cillum occaecat an deserunt. Eu labore laborum cohaerescant. Do 
                non aliqua iudicem de arbitror anim culpa aliquip magna. Sint probant 
                tractavissent, eiusmod sunt expetendis et aut illum sint elit excepteur ita amet 
                expetendis mandaremus. Aliqua laborum exercitation et ipsum ita occaecat ad 
                culpa ingeniis id summis fugia.<br>
                Nulla a te lorem nostrud. Nostrud 
                a fugiat laboris, o velit quae summis mandaremus, hic ita nulla magna quem an 
                magna ingeniis id summis fugiat. Enim fabulas cernantur.
            </p>
        </div>
        <div class="img">
            <%= image_tag("sobre_ilustra.png") %>
        </div>
    </div>
</div>

<div class="section3">
    <div class="ct">
        <h1>Anunciantes</h1>
        <p>
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
        </p>
        
        <table>
            <tr>
                <td>
                    <%= image_tag("exemplo1.jpg") %>
                </td>
                <td>
                    <strong>Azuma:</strong> Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
                </td>
            </tr>
            <tr><td colspan="2"><br></td></tr>
            <tr>
                <td>
                    <%= image_tag("exemplo2.jpg") %>
                </td>
                <td>
                    <strong>Toyota:</strong> Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
                </td>
            </tr>
            <tr><td colspan="2"><br></td></tr>
            <tr>
                <td>
                    <%= image_tag("exemplo3.jpg") %>
                </td>
                <td>
                    <strong>Tomato Bank:</strong> Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur.
                </td>
            </tr>

        </table>
    </div>
</div>

<div class="section4">
    <div class="ct">
        <div class="text">
            <h1>Como Anunciar</h1>
            <p>
                Qui an minim iudicem, ab fore ea dolore, se mandaremus voluptatibus iis vidisse 
                imitarentur ne laborum. Singulis nisi varias probant fore, ita noster 
                cohaerescant. Cillum occaecat an deserunt.<br><br> Eu labore laborum cohaerescant. Do 
                non aliqua iudicem de arbitror anim culpa aliquip magna. Sint probant 
                tractavissent, eiusmod sunt expetendis et aut illum sint elit excepteur ita amet 
                expetendis mandaremus. Aliqua laborum exercitation et ipsum ita occaecat ad 
                culpa ingeniis id summis fugia.<br>
                Nulla a te lorem nostrud. Nostrud 
                a fugiat laboris, o velit quae summis mandaremus, hic ita nulla magna quem an 
                magna ingeniis id summis fugiat. Enim fabulas cernantur.
            </p>
        </div>
        <div class="img">
            <%= image_tag("como_ilustra.png") %>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<% if params[:tag] && @posts.empty? %>
  <div class='box'>
    <p class='no-posts-message'>Desculpe, no momento não temos nenhum anúncio publicado para a região de <strong><%= params[:tag].capitalize %></strong>, mas temos outras <%= link_to 'oportunidades!', root_path %></p>
  </div>
<% end %>

<% if @posts.empty? %>
  <div class='box'>
    <p class='no-posts-message'>Nenhum anúncio publicado.</p>
  </div>
<% end %>

<ol class='articles-list'>
  <% @posts.each do |post| %>
    <li>
  <article class='article box'>
    <%= ribbon(post) %>
    <h1 class='article-title'>
      <i class='fa fa-star star-color'></i>
      <%= link_to(post.title, post_url(post), title: post.title) %>
    </h1>

    <div class='article-body'>
      <p class='article-location'>
      <%= post.location %>
      </p>
      <p class='article-description'>
      <%= post.short_description %>
      </p>

      <ul class='article-social-and-tags'>
        <li>
        <%= link_to post_url(post), class: 'facebook-share-button', alt: 'Compartilhar no Facebook' do %>
          <i class='fa fa-facebook-square fa-2 facebook-color'></i>
      <% end %>
        </li>
        <li>
        <%= link_to post_url(post), title: "#{post.title} @shigotodoko", class: 'twitter-share-button', target: '_blank', rel: 'external', alt: 'Compartilhar via Twitter' do %>
          <i class='fa fa-twitter-square fa-2 twitter-color'></i>
      <% end %>
        </li>
        <li>
        <%= link_to post_url(post), class: 'google-plus-share-button', target: '_blank', rel: 'external', alt: 'Compartilhar no Google+' do %>
          <i class='fa fa-google-plus-square fa-2 google-plus-color'></i>
      <% end %>
        </li>
      </ul>

      <time class='article-published-date' datetime='<%= post.published_at %>'>
        <%= time_ago_in_words(post.published_at) %> atrás
      </time>
    </div>
  </article>
  </li>
<% end %>
</ol>

<div class='pagination'>
  <%= will_paginate(@posts) %>
</div>

<% content_for(:aside) do %>
  <%= render 'aside' %>
<% end %>

app/views/posts/new.html.erb
<% title 'Novo anúncio' %>

<% if @post.errors.any? %>
  <div class="error_explanation">
  <h3 class='headline'>Por favor verifique as informações abaixo:</h3>
  <ul class='square'>
    <% @post.errors.full_messages.each do |msg| %>
      <li class='error_field'><%= msg %></li>
  <% end %>
  </ul>
  </div>
<% end %>

<%= form_for(@post) do |f| %>
  <div class='box new-post-box'>
  <h1 class='new-post-title'>Novo Anúncio</h1>
  <!-- title -->
  <p class='new-post title'>
  <label for='post-title'>Título do anúncio</label>
  <%= f.text_field :title, placeholder: 'Exemplo: Auto-peças' %>
  </p>
  <!-- location -->
  <p class='new-post location'>
  <label for='post-location'>Local de Trabalho</label>
  <%= f.text_field :location, placeholder: 'Aichi-ken, Toyohashi-shi' %>
  </p>
  <!-- description -->
  <p class='new-post description'>
  <label for='post-description'>Descreva o trabalho a ser realizado:</label>
  <%= f.text_area :description, rows: 10, placeholder: "Máximo 400 caracteres." %>
  </p>
  <!-- salary -->
  <p class='new-post salary'>
  <label for='post-salary'>Remuneração/hora</label>
  <%= f.text_field :salary, placeholder: 'Exemplo: 1.200 ienes/hora' %>
  </p>
  <!-- shift -->
  <p class='new-post shift'>
  <label for='post-shift'>Período/Turno</label>
  <%= f.text_field :shift, placeholder: 'Exemplo: Diurno ou Noturno' %>
  </p>
  <!-- workload -->
  <p class='new-post workload'>
  <label for='post-workload'>Horário de Trabalho</label>
  <%= f.text_field :work_load, placeholder: 'Exemplo: das 08:00 às 17:00' %>
  </p>
  <!-- dayoff -->
  <p class='new-post dayoff'>
  <label for='post-dayoff'>Dias de Folga</label>
  <%= f.text_field :day_off, placeholder: 'Sábados e domingos' %>
  </p>
  <!-- requisites -->
  <p class='new-post requirements'>
  <label for='post-requirements'>Requisitos:</label>
  <%= f.text_area :requirements, rows: 10, placeholder: "Máximo 400 caracteres." %>
  </p>
  <!-- benefits -->
  <p class='new-post benefits'>
  <label for='post-benefits'>Benefícios:</label>
  <%= f.text_area :benefits, rows: 10, placeholder: "Máximo 400 caracteres." %>
  </p>
</div>

<div class='box new-post-box'>
  <h1 class='new-post-title'>Dados do anunciante</h1>
  <!-- contractor name -->
  <p class='contractor person-name'>
  <label for='contractor-person-name'>Nome do responsável pelo anúncio:</label>
  <%= f.text_field :contractor_person_name %>
  </p>
  <!-- company name -->
  <p class'contractor company-name'>
  <label for='company-name'>Nome da Empresa anunciante:</label>
  <%= f.text_field :contractor_company_name %>
  </p>
  <!-- company-address -->
  <p class='contractor company-address'>
  <label for='company-address'>Endereço da Empresa:</label>
  <%= f.text_field :contractor_address %>
  </p>
  <!-- contact-email -->
  <p class='contractor company-email'>
  <label for='company-email'>E-mail da empresa para contato:</label>
  <%= f.text_field :contractor_mail_address %>
  </p>
  <!-- contact-phone -->
  <p class='contractor company-phone'>
  <label for='company-phone'>Telefone da empresa para contato:</label>
  <%= f.text_field :contractor_phone_number %>
  </p>

  <p class='post-info'>Seu anúncio ficará disponível por no mínimo 30 dias a contar da data de publicação.</p>
  <p class='post-info'>A publicação ocorre após um período de avaliação de no máximo 7 dias úteis. Caso seu anúncio não seja publicado dentro do período informado favor entrar em contato pelo e-mail shigotodoko@gmail.com</p>

  <%= submit_tag('Enviar', name: 'submit', class: 'send-button', data: { disable_with: 'Enviando...' }) %>
</div>
<% end %>

app/views/posts/success.html.erb
<% title "Obrigado por enviar um anúncio para o ShigotoDoko" %>

<div class="box success-page">
  <h1 class='title'>Obrigado por enviar um anúncio para o ShigotoDoko!</h1>
  <p>Seu anúncio ficará disponível por no mínimo 30 dias a contar da data de publicação.</p>
  <p>A publicação ocorre após um período de avaliação de no máximo 7 dias úteis. </p>

  <hr>

  <p>Caso seu anúncio não seja publicado dentro do período informado favor entrar em contato pelo e-mail <%= mail_to "shigotodoko@gmail.com" %></p>

  <p class='feedback'><%= link_to 'Quero participar do Feedback!', feedback_path, class: 'btn btn-block btn-lg btn-success' %></p>
</div>

app/views/posts/tags.html.erb
<% title("Empregos no Japão em #{params[:tag]}") %>