config/routes.rb
Rails.application.routes.draw do
  get '/admin' => redirect("/users/sign_in")
  devise_for :users, controllers: { sessions: 'admin/sessions' }

  namespace :api do
    get '/posts/published', to: 'posts#published'
  end

  namespace :admin do
    resources :posts do
      put :publish, on: :member
      put :archive, on: :member
    end

    resources :contractors do
      resources :contacts
    end
    get 'contacts/:contractor_name', to: 'contacts#show'
  end

  root :to => 'posts#index'

  resources :posts, only: [:index, :show, :new, :create] do
    collection do
      get  :feeds, defaults: { format: 'rss' }
      post :tweet
      get :home
    end
  end
  get 'posts/tags/:tag', to: 'posts#tags', as: 'posts_tag_filter'

  get '/obrigado-anuncio-enviado-com-sucesso' => 'posts#success', as: :post_success

  get '/feedback', to: 'home#feedback', as: :feedback
end

app/views/layouts/admin.html.erb
<html>
  <head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'admin' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to "Nova", new_admin_contractor_path %></li>
    <li><%= link_to "Lista", admin_contractors_path %></li>
  </ul>
    <nav class="indigo darken-4" role="navigation">
      <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo"><%= link_to 'Admin', admin_posts_path %></a>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to "Anúncios", admin_posts_path %></li>
          <!-- Dropdown Trigger -->
          <li>
            <a class="dropdown-button" href="#!" data-activates="dropdown1">Empresas<i class="material-icons right">arrow_drop_down</i></a>
          </li>
          <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><a href="#">Navbar Link</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>


    <div class="container">
      <div class="section">
        <%= yield %>
      </div>
    </div>

    <footer class="page-footer orange">
      <div class="container">
        <div class="row">
          <div class="col l3 s12">
            <h5 class="white-text">Anúncios</h5>
            <ul>
              <li><%= link_to "Todos os anúncios", admin_posts_path, class: "white-text" %></li>
            </ul>
          </div>
          <div class="col l3 s12">
            <h5 class="white-text">Site</h5>
            <ul>
              <li><a class="white-text" href="https://www.shigotodoko.com">Ir para o site</a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='pt-br'>
<head>
  <meta charset='utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="google-site-verification" content="culxN0GN5f_GZnPGAr0AJ1QyJxfKXNRyty9-9fQFtGA" />
  <%= yield(:meta) %>
  <title><%= content_for?(:title) ? content_for(:title) : "Empregos no Japão" %></title>
  <%= stylesheet_link_tag 'application' %>
  <%= auto_discovery_link_tag(:rss, "https://feeds.feedburner.com/ShigotoDoko" )%>
  <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/2.0.8/es5-shim.min.js"></script><![endif]-->
  </head>

<body>
  <header>
    <div class='container'>
      <%= link_to(image_tag('logo_top_plano.png', alt: 'logo', title: 'logo'), root_path) %>
    </div>
  </header>

  <section class='search-mobile'>
    <form class='container'>
      <fieldset>
        <%= select_tag 'prefecture_filter',
          options_for_select(Shigotodoko::Prefecture.all)
        %>
      </fieldset>
    </form>
  </section>

  <%= top_banner %>

  <div class='wrapper container'>
    <main>
    <%= yield %>
    </main>

    <aside>
      <%= yield(:aside) %>
    </aside>

  </div><!-- /wrapper -->

  <div class='ad-320-568 footer align-mobile-ad'>
    <!-- 320x100 - mobile home footer -->
    <ins class="adsbygoogle"
      style="display:inline-block;width:320px;height:100px"
      data-ad-client="ca-pub-1679261120441100"
      data-ad-slot="3714599619"></ins>
    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
  </div>

  <div class='ad-from-768 footer align-mobile-ad'>
    <!-- (new) 728x90 - main/posts/footer -->
    <ins class="adsbygoogle"
      style="display:inline-block;width:728px;height:90px"
      data-ad-client="ca-pub-1679261120441100"
      data-ad-slot="9871469613"></ins>
    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
  </div>

  <div class='follow-network container'>
    <span class='title'>Siga o ShigotoDoko nas redes sociais</span>
    <ul class='social-networks'>
      <li>
      <a class='sprite-facebook sprite-social-media' href='https://facebook.com/ShigotoDoko'>Facebook</a>
      </li>
      <li>
      <a class='sprite-twitter sprite-social-media' href='https://twitter.com/shigotodoko'>Twitter</a>
      </li>
      <li>
      <a class='sprite-google-plus sprite-social-media' href='https://plus.google.com/b/111043374287269601303'>Google+</a>
      </li>
    </ul>
  </div>

  <div class='partners-mobile container'>
    <section class='partners-section box'>
    <h3>Links Parceiros</h3>
    <h4>
      <a href='http://www.japaoemfoco.com/como-receber-o-reembolso-da-aposentadoria-no-brasil?utm_source=shigotodoko' target='_blank'>Saiba como receber o reembolso da aposentadoria no Brasil</a>
    </h4>
    </section>
  </div>

  <footer>
    <div class='container'>
      <span class='small'>Copyright © ShigotoDoko <%= Date.today.year %>. All Rights Reserved</span>
    </div>
  </footer>

  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <%= javascript_include_tag 'selectize', async: true %>
  <%= javascript_include_tag 'application', asycn: true %>

  <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.5.18/webfont.js"></script>
  <script>
  WebFont.load({
    google: {
      families: ['Open Sans:400']
    }
  });
  </script>

  <!-- Google Analytics -->
  <script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-4430385-2']);
_gaq.push(['_trackPageview']);

(function() {
 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
 var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
 })();
  </script>

</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html lang='pt-br'>
  <head>
    <meta charset='utf-8'>
    <title>ShigotoDoko Administration</title>
    <link href="//fonts.googleapis.com/css?family=Oxygen:400,700" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag("sessions") %>
  </head>
  <body>
    <div class="container">
      <h1>ShigotoDoko Site Administration</h1>
      <%= yield %>
    </div>
  </body>
</html>